services:
  - type: web
    name: potomitan
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 18
