services:
  - type: web
    name: potomitan
    env: node
    plan: free
    # 1) Installe les dépendances et build le frontend Vue
    buildCommand: npm install && npm run build
    # 2) Lance uniquement le server Express qui sert à la fois l’API et le dist/
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 18
